#!/usr/bin/env python3
"""
subset_emoji.py — Build a Noto Color Emoji subset font and matching
Avalonia FontFallback snippet from a sample text file.

Usage:
    python subset_emoji.py \
        --font NotoColorEmoji-Regular.ttf \
        --samples emoji_samples.txt \
        --out-font NotoColorEmoji.Subset.ttf \
        --out-cs GlobalFonts.Emoji.g.cs \
        [--font-family-ref NotoColorEmoji] \
        [--namespace MyApp.Fonts]

The samples file may contain any text — every Unicode scalar value found in it
(except ASCII whitespace) is added to the subset. Multi-codepoint sequences
(ZWJ emoji, flags, skin-tone modifiers, keycaps) are handled automatically
because each component codepoint appears in the source text.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import unicodedata
from pathlib import Path


# Codepoints we always want to keep around so sequences render correctly,
# even if the user's sample file happens not to contain them explicitly.
ALWAYS_INCLUDE = {
    0x200D,  # ZERO WIDTH JOINER
    0xFE0E,  # VARIATION SELECTOR-15 (text presentation)
    0xFE0F,  # VARIATION SELECTOR-16 (emoji presentation)
    0x20E3,  # COMBINING ENCLOSING KEYCAP
}


def read_codepoints(samples_path: Path) -> set[int]:
    """Extract every non-trivial codepoint from the samples file.

    Comments are supported:
      * Lines whose first non-whitespace character is '#' are skipped entirely.
      * On any other line, everything from the first '#' to end-of-line is
        stripped before codepoints are collected.

    To include a literal '#' as a glyph, escape it as '\\#'.
    """
    codepoints: set[int] = set()
    for raw_line in samples_path.read_text(encoding="utf-8").splitlines():
        # Whole-line comment.
        if raw_line.lstrip().startswith("#"):
            continue

        # Strip trailing '# ...' comment, honoring '\#' as an escape.
        line_chars: list[str] = []
        i = 0
        while i < len(raw_line):
            ch = raw_line[i]
            if ch == "\\" and i + 1 < len(raw_line) and raw_line[i + 1] == "#":
                line_chars.append("#")
                i += 2
                continue
            if ch == "#":
                break  # rest of line is a comment
            line_chars.append(ch)
            i += 1

        for ch in line_chars:
            cp = ord(ch)
            # Skip ASCII whitespace and control chars; keep everything else.
            if cp < 0x20 or cp == 0x7F:
                continue
            if ch in (" ", "\t"):
                continue
            codepoints.add(cp)

    codepoints.update(ALWAYS_INCLUDE)
    return codepoints


def coalesce_ranges(codepoints: set[int]) -> list[tuple[int, int]]:
    """Turn a set of codepoints into a list of contiguous (start, end) ranges."""
    if not codepoints:
        return []
    sorted_cps = sorted(codepoints)
    ranges: list[tuple[int, int]] = []
    start = prev = sorted_cps[0]
    for cp in sorted_cps[1:]:
        if cp == prev + 1:
            prev = cp
            continue
        ranges.append((start, prev))
        start = prev = cp
    ranges.append((start, prev))
    return ranges


def run_pyftsubset(
    font_path: Path,
    out_path: Path,
    codepoints: set[int],
) -> None:
    """Invoke pyftsubset to produce the subset font, preserving color tables."""
    unicodes_arg = ",".join(f"U+{cp:04X}" for cp in sorted(codepoints))
    cmd = [
        sys.executable, "-m", "fontTools.subset",
        str(font_path),
        f"--unicodes={unicodes_arg}",
        f"--output-file={out_path}",
        # Keep layout features that matter for emoji sequences.
        "--layout-features+=ccmp,liga,rlig,rclt,calt",
        # Keep the .notdef glyph valid so the font is well-formed.
        "--notdef-outline",
        # Drop hinting / unused name records to shrink the file.
        "--no-hinting",
        "--name-IDs=*",
        "--glyph-names",
        # Recalculate so the OS/2 unicode ranges reflect the subset.
        "--recalc-bounds",
        "--recalc-timestamp",
    ]
    print("Running:", " ".join(cmd))
    subprocess.run(cmd, check=True)


def format_cs_file(
    ranges: list[tuple[int, int]],
    namespace: str,
    font_family_ref: str,
) -> str:
    """Render the GlobalFonts partial class with EmojiFallbacks."""
    lines: list[str] = []
    lines.append("// <auto-generated />")
    lines.append("// Generated by subset_emoji.py — do not edit by hand.")
    lines.append("using System.Collections.Generic;")
    lines.append("using Avalonia.Media;")
    lines.append("using Avalonia.Media.Fonts;")
    lines.append("")
    lines.append(f"namespace {namespace};")
    lines.append("")
    lines.append("public static partial class GlobalFonts")
    lines.append("{")
    lines.append("    private static IEnumerable<FontFallback> EmojiFallbacks =>")
    lines.append("    [")

    for i, (start, end) in enumerate(ranges):
        comma = "," if i < len(ranges) - 1 else ""
        comment = describe_range(start, end)
        lines.append("        new FontFallback()")
        lines.append("        {")
        lines.append(f"            FontFamily = {font_family_ref},")
        lines.append(
            f"            UnicodeRange = new UnicodeRange(0x{start:04X}, 0x{end:04X})"
        )
        lines.append(f"        }}{comma} // {comment}")

    lines.append("    ];")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def describe_range(start: int, end: int) -> str:
    """Best-effort human label for a range, using Unicode names of the endpoints."""
    try:
        start_name = unicodedata.name(chr(start))
    except ValueError:
        start_name = f"U+{start:04X}"
    if start == end:
        return start_name
    try:
        end_name = unicodedata.name(chr(end))
    except ValueError:
        end_name = f"U+{end:04X}"
    return f"{start_name} … {end_name}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", required=True, type=Path,
                        help="Path to the source Noto Color Emoji TTF.")
    parser.add_argument("--samples", required=True, type=Path,
                        help="Text file containing every emoji you want to support.")
    parser.add_argument("--out-font", required=True, type=Path,
                        help="Destination path for the subset TTF.")
    parser.add_argument("--out-cs", required=True, type=Path,
                        help="Destination path for the generated .cs file.")
    parser.add_argument("--namespace", default="MyApp.Fonts",
                        help="Namespace for the generated GlobalFonts class.")
    parser.add_argument("--font-family-ref", default="NotoColorEmoji",
                        help="C# expression used as the FontFamily value "
                             "(e.g. a static property name).")
    args = parser.parse_args()

    if not args.font.is_file():
        print(f"error: source font not found: {args.font}", file=sys.stderr)
        return 1
    if not args.samples.is_file():
        print(f"error: samples file not found: {args.samples}", file=sys.stderr)
        return 1

    codepoints = read_codepoints(args.samples)
    if not codepoints:
        print("error: no usable codepoints found in samples file", file=sys.stderr)
        return 1

    print(f"Found {len(codepoints)} unique codepoints in samples.")
    ranges = coalesce_ranges(codepoints)
    print(f"Coalesced into {len(ranges)} contiguous range(s).")

    args.out_font.parent.mkdir(parents=True, exist_ok=True)
    run_pyftsubset(args.font, args.out_font, codepoints)
    print(f"Wrote subset font: {args.out_font} "
          f"({args.out_font.stat().st_size:,} bytes)")

    cs = format_cs_file(ranges, args.namespace, args.font_family_ref)
    args.out_cs.parent.mkdir(parents=True, exist_ok=True)
    args.out_cs.write_text(cs, encoding="utf-8")
    print(f"Wrote C# fallback snippet: {args.out_cs}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
